<script setup>
import { ref, reactive, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import I from './components/AppIcon.vue'
import AvatarFigure from './components/AvatarFigure.vue'
import AvatarStudio from './components/AvatarStudio.vue'
import VisualNovel from './components/VisualNovel.vue'
import { places, modes, sources } from './data/world'
import { questions } from './data/questions'
import { soundEnabled, toggleSound, sfx, speak, setScene } from './audio'

const STORAGE='star-city-preview-v1'
const defaults={name:'星城探索者',avatar:{gender:'female',hair:0,suit:0,color:'#754b32'},mode:'city',points:0,completed:[],correct:[],mistakes:[],checkins:[],redeemed:[],daily:'',diary:'',ticket:false,likes:[]}
let saved={}
try{saved=JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{}
const state=reactive({...structuredClone(defaults),...saved})
for(const key of ['completed','correct','mistakes','checkins','redeemed','likes'])if(!Array.isArray(state[key]))state[key]=[]
state.points=Number.isFinite(state.points)?Math.max(0,state.points):0
if(!modes.some(m=>m.id===state.mode))state.mode='city'
const nav=[{id:'home',name:'探索首页',icon:'Home'},{id:'map',name:'城市地图',icon:'Map'},{id:'story',name:'剧本故事',icon:'BookOpen'},{id:'classroom',name:'反诈课堂',icon:'ShieldCheck'},{id:'avatar',name:'我的数字形象',icon:'Palette'},{id:'rewards',name:'星启好礼',icon:'Gift'},{id:'community',name:'星启社区',icon:'MessageCircle'}]
const validPages=[...nav.map(n=>n.id),'profile']
const page=ref(validPages.includes(location.hash.slice(1))?location.hash.slice(1):'home')
const toast=ref(''),modal=ref(''),selected=ref(places[1]),scale=ref(1),guideOpen=ref(false),classFilter=ref('全部'),questionSearch=ref(''),scanPlace=ref('wuyi'),shareText=ref(''),nameDraft=ref(state.name),dialogEl=ref(null)
let toastTimer,restoreFocus
const currentMode=computed(()=>modes.find(m=>m.id===state.mode))
const routePlaces=computed(()=>currentMode.value.ids.map(id=>places.find(p=>p.id===id)))
const routeDone=computed(()=>routePlaces.value.filter(p=>state.completed.includes(p.id)).length)
const coreDone=computed(()=>places.slice(0,6).filter(p=>state.completed.includes(p.id)).length)
const activePlace=computed(()=>routePlaces.value.find(p=>!state.completed.includes(p.id))||routePlaces.value[0])
const level=computed(()=>coreDone.value>=6?'金融守护者':coreDone.value>=3?'城市足迹官':'初阶探索者')
const progress=computed(()=>Math.round(coreDone.value/6*100))
const today=()=>new Date().toLocaleDateString('sv-SE')
const routePath=computed(()=>routePlaces.value.map(p=>`${p.x},${p.y}`).join(' '))
const filteredQuestions=computed(()=>questions.filter(q=>(classFilter.value==='全部'||classFilter.value==='错题本'&&state.mistakes.includes(q.id)||q.category===classFilter.value)&&q.title.includes(questionSearch.value)))
const lesson=reactive({active:false,phase:'intro',place:null,list:[],index:0,selected:null,submitted:false,score:0,practice:false,gained:0,passed:false,newComplete:false})
const currentQ=computed(()=>lesson.list[lesson.index])
const rewards=[{id:'coffee',title:'星城咖啡体验券',desc:'一杯咖啡，一段街巷时光',cost:60,icon:'Coffee',color:'sand'},{id:'postcard',title:'长沙限定数字明信片',desc:'把湘江晚风装进口袋',cost:20,icon:'Landmark',color:'mint'},{id:'bike',title:'城市骑行体验券',desc:'沿着湘江，向快乐出发',cost:120,icon:'Bike',color:'sky'}]
const posts=[{id:1,name:'小林同学',school:'星启体验官',title:'原来 Citywalk 还可以这样玩',text:'从五一广场走到潮宗街，一路攒印章、解谜题。今天记住了：陌生客服发来的积分链接，先别点！',tag:'#我的星城探索日记',cover:'route-city.png',likes:26},{id:2,name:'橘子汽水',school:'星启体验官',title:'给我的数字分身换了个新发色',text:'一头薄荷绿，搭配老街国风装扮。下一站，和工小智一起去江边吹风。',tag:'#我的镜界穿搭',cover:'avatar',likes:18}]
watch(state,()=>{try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{notify('浏览器存储不可用，本次进度暂时保留在页面中。')}},{deep:true})
watch(page,p=>{setScene('explore');if(p==='avatar')speak('avatar')})
watch(modal,async value=>{if(value){restoreFocus=document.activeElement;await nextTick();dialogEl.value?.focus()}else restoreFocus?.focus?.()})
function notify(message){toast.value=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',3200)}
function go(id){if(!validPages.includes(id))return;lesson.active=false;modal.value='';page.value=id;location.hash=id;sfx('transition');window.scrollTo({top:0,behavior:'instant'})}
function onHash(){const p=location.hash.slice(1);if(validPages.includes(p)){page.value=p;lesson.active=false;modal.value='';setScene('explore')}}
function openModal(id){if(id==='diary')shareText.value=state.diary||'';modal.value=id;sfx('click')}
function chooseMode(mode){state.mode=mode;selected.value=activePlace.value;scale.value=1;go('map')}
function inspectPlace(place){selected.value=place;sfx('click');if(window.innerWidth<=640)nextTick(()=>document.querySelector('.selected-place-card')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function openStory(place){selected.value=place;lesson.active=true;lesson.phase='story';lesson.place=place;lesson.practice=false;lesson.list=questions.filter(q=>q.place===(place.id==='pozi'?'chaozong':place.id)).slice(0,3);setScene('story');sfx('click');speak('alert');window.scrollTo({top:0,behavior:'instant'})}
function startPractice(list=filteredQuestions.value){if(!list.length){notify('这里还没有题目，先去开启一次挑战吧。');return}lesson.active=true;lesson.place=null;lesson.practice=true;lesson.list=[...list];beginQuiz()}
function beginQuiz(){Object.assign(lesson,{phase:'quiz',index:0,selected:null,submitted:false,score:0,gained:0,passed:false,newComplete:false});setScene('quiz');window.scrollTo({top:0,behavior:'instant'})}
function submitAnswer(){
 if(lesson.selected===null||lesson.submitted)return
 lesson.submitted=true
 const q=currentQ.value
 if(lesson.selected===q.answer){lesson.score++;if(!state.correct.includes(q.id)){state.correct.push(q.id);state.points+=10;lesson.gained+=10}state.mistakes=state.mistakes.filter(id=>id!==q.id);sfx('correct')}
 else {if(!state.mistakes.includes(q.id))state.mistakes.push(q.id);sfx('wrong')}
}
function nextQuestion(){
 if(!lesson.submitted)return
 if(lesson.index<lesson.list.length-1){lesson.index++;lesson.selected=null;lesson.submitted=false;return}
 lesson.phase='result';lesson.passed=lesson.score>=Math.ceil(lesson.list.length*2/3)
 if(!lesson.practice&&lesson.passed&&!state.completed.includes(lesson.place.id)){state.completed.push(lesson.place.id);state.points+=20;lesson.gained+=20;lesson.newComplete=true;sfx('unlock')}
 setScene(lesson.passed?'victory':'explore')
}
function leaveLesson(){lesson.active=false;setScene('explore');go(lesson.practice?'classroom':'map')}
function claimDaily(){if(state.daily===today()){notify('今天已签到，明天再来领取。');return}state.daily=today();state.points+=10;sfx('points');notify('今日签到成功，+10 体验 i豆！')}
function redeem(reward){if(state.redeemed.includes(reward.id)){notify('已在你的背包中，去查看兑换凭证吧。');return}if(state.points<reward.cost){notify(`还差 ${reward.cost-state.points} i豆，去挑战赚取吧。`);return}state.points-=reward.cost;state.redeemed.push(reward.id);sfx('points');notify('兑换成功！演示权益已放入我的背包。')}
function checkIn(){if(state.checkins.includes(scanPlace.value)){notify('这个地标已记录打卡。');return}state.checkins.push(scanPlace.value);sfx('unlock');notify('模拟打卡成功，城市足迹已记录。')}
function activateTicket(){if(coreDone.value<6||!state.checkins.length){notify('完成六大地标挑战，并至少模拟打卡一次后可激活。');return}state.ticket=true;notify('演示抽奖资格已激活，资格卡已放入背包。')}
async function audioToggle(){if(!await toggleSound())notify('音乐暂时未加载完成，请稍后再试。');else if(soundEnabled.value)notify('纯音乐已开启，可随时关闭。')}
function saveAvatar(value){if(value)state.avatar={...value};notify('数字形象已保存，带着新造型出发吧！')}
function saveName(){state.name=nameDraft.value.trim().slice(0,12)||'星城探索者';modal.value='';notify('探索者昵称已更新。')}
function like(id){state.likes=state.likes.includes(id)?state.likes.filter(x=>x!==id):[...state.likes,id]}
function share(){if(!shareText.value.trim()){notify('先写下你的探索心情吧。');return}state.diary=shareText.value.trim().slice(0,400);notify('日记已保存到本机，不会发布到外部平台。');modal.value=''}
function resetProgress(){Object.assign(state,structuredClone(defaults));modal.value='';go('home');notify('体验进度已重置，可以从头探索。')}
function downloadPassport(){
 const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const c=canvas.getContext('2d')
 c.fillStyle='#f7f4e9';c.fillRect(0,0,900,1200);c.strokeStyle='#c3a36a';c.lineWidth=3;c.strokeRect(38,38,824,1124);c.strokeRect(50,50,800,1100)
 c.textAlign='center';c.fillStyle='#22324f';c.font='22px sans-serif';c.fillText('工银星启 · 智游镜界',450,116);c.font='bold 58px sans-serif';c.fillText(coreDone.value===6?'城市金融守护者':'星城探索护照',450,255);c.font='24px sans-serif';c.fillStyle='#8c774e';c.fillText('CHANGSHA EXPLORER PASSPORT',450,310)
 c.fillStyle='#22324f';c.font='bold 40px sans-serif';c.fillText(state.name,450,426);c.font='24px sans-serif';c.fillText(`已守护 ${coreDone.value} / 6 座城市地标`,450,486)
 places.slice(0,6).forEach((p,i)=>{const x=225+(i%2)*450,y=615+Math.floor(i/2)*126;c.fillStyle=state.completed.includes(p.id)?'#237b73':'#a8adb3';c.beginPath();c.arc(x,y,35,0,Math.PI*2);c.strokeStyle=c.fillStyle;c.lineWidth=2;c.stroke();c.font='22px sans-serif';c.fillText(state.completed.includes(p.id)?'已守护':'待探索',x,y+8);c.font='22px sans-serif';c.fillText(p.name,x,y+68)})
 c.fillStyle='#8d8e92';c.font='19px sans-serif';c.fillText(`签发日期 ${today()}  ·  参赛体验凭证`,450,1070);c.font='17px sans-serif';c.fillText('仅作项目演示，不作为官方认证或真实权益凭证',450,1108)
 const a=document.createElement('a');a.download='智游镜界-城市探索护照.png';a.href=canvas.toDataURL('image/png');a.click();notify('城市探索护照已生成。')
}
function keyHandler(e){
 if(e.key==='Escape'){if(modal.value)modal.value='';else if(lesson.active)leaveLesson()}
 if(e.key==='Tab'&&modal.value&&dialogEl.value){const f=[...dialogEl.value.querySelectorAll('button:not(:disabled),a,input,select,textarea,[tabindex="0"]')];if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialogEl.value)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
}
onMounted(()=>{window.addEventListener('hashchange',onHash);window.addEventListener('keydown',keyHandler)})
onUnmounted(()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('keydown',keyHandler);clearTimeout(toastTimer)})
</script>

<template>
 <div class="app-shell">
  <aside class="sidebar">
   <button class="brand" @click="go('home')" aria-label="智游镜界首页"><span class="brand-mark">✦</span><span><b>智游镜界</b><small>工银星启 · STAR JOURNEY</small></span></button>
   <div class="sidebar-label">你的城市冒险，从这里开始</div>
   <nav class="side-nav" aria-label="主导航"><button v-for="item in nav" :key="item.id" :class="{active:page===item.id}" @click="go(item.id)"><I :name="item.icon" :size="20"/><span>{{item.name}}</span><i v-if="page===item.id"/></button></nav>
   <button class="side-challenge" @click="openStory(activePlace)"><span class="mini-label">THE CITY IS CALLING</span><h3>星城，需要你的守护。</h3><p>和工小智一起<br>解锁城市的另一面</p><img src="/assets/mascot.png" alt="工小智"><span class="side-link">继续探索 <I name="ArrowRight" :size="15"/></span></button>
   <div class="sidebar-bottom"><span class="icbc-symbol">工</span><div><b>工银星启</b><small>第十七届「工行杯」参赛作品</small></div></div>
  </aside>
  <div class="workspace">
   <header class="topbar"><div class="breadcrumb"><span class="desktop-only">智游镜界 <span class="crumb-slash">/</span></span><b>{{nav.find(n=>n.id===page)?.name||'我的探索'}}</b><span class="preview-badge">体验预览版</span></div><div class="header-actions"><span class="location"><I name="MapPin" :size="15"/>中国 · 长沙</span><button class="icon-button" :aria-label="soundEnabled?'关闭音乐':'开启音乐'" :title="soundEnabled?'关闭音乐':'开启纯音乐'" @click="audioToggle"><I :name="soundEnabled?'Volume2':'VolumeX'"/></button><button class="icon-button bell" aria-label="查看消息" @click="openModal('messages')"><I name="Bell"/><i/></button><button class="user-chip" @click="go('profile')"><span class="user-face"><AvatarFigure :model-value="state.avatar" compact /></span><span class="desktop-only">{{state.name}}</span><I name="ChevronRight" :size="14"/></button></div></header>

   <main v-if="lesson.active" class="lesson-page page-enter">
    <button class="back-link" @click="leaveLesson"><I name="ChevronLeft" :size="18"/>{{lesson.practice?'返回反诈课堂':'返回城市地图'}}</button>
    <template v-if="lesson.phase==='story'">
     <VisualNovel :place="lesson.place" @complete="beginQuiz" />
     <div class="lesson-actions"><span>剧情线索会在答题中转化为你的判断</span><button class="secondary" @click="beginQuiz">跳过剧情，直接挑战 <I name="ArrowRight" :size="18"/></button></div>
    </template>
    <template v-else-if="lesson.phase==='quiz'">
     <div class="quiz-top"><div><span class="eyebrow">{{lesson.practice?'金融安全训练':'镜界风险调查'}} · {{currentQ.category}}</span><h1>{{lesson.practice?'每一点知识，都是守护的力量。':lesson.place.name+' · 线索解密'}}</h1></div><span class="question-count"><b>{{String(lesson.index+1).padStart(2,'0')}}</b> / {{String(lesson.list.length).padStart(2,'0')}}</span></div>
     <div class="progress-track"><i :style="{width:(lesson.index/lesson.list.length*100)+'%'}"/></div>
     <div class="quiz-layout"><section class="question-card"><span class="tag blue-tag">单选题 · 首次答对 +10 i豆</span><h2>{{currentQ.title}}</h2><div class="answer-options"><button v-for="(option,index) in currentQ.options" :key="currentQ.id+'-'+index" :disabled="lesson.submitted" :class="{chosen:lesson.selected===index,correct:lesson.submitted&&index===currentQ.answer,wrong:lesson.submitted&&lesson.selected===index&&index!==currentQ.answer}" @click="lesson.selected=index"><b>{{'ABC'[index]}}</b><span>{{option}}</span><I v-if="lesson.submitted&&index===currentQ.answer" name="Check"/><I v-else-if="lesson.submitted&&lesson.selected===index" name="X"/></button></div><div v-if="lesson.submitted" class="answer-explanation" :class="{incorrect:lesson.selected!==currentQ.answer}" role="status"><b><I :name="lesson.selected===currentQ.answer?'ShieldCheck':'CircleHelp'" :size="20"/>{{lesson.selected===currentQ.answer?'判断正确，成功识别风险！':'差一点，看看风险藏在哪里'}}</b><p>{{currentQ.explanation}}</p><a :href="sources[currentQ.source].url" target="_blank" rel="noreferrer">知识参考 · {{sources[currentQ.source].title}} <I name="ExternalLink" :size="12"/></a></div><button v-if="!lesson.submitted" class="primary full" :disabled="lesson.selected===null" @click="submitAnswer">确认我的判断 <I name="ArrowRight" :size="18"/></button><button v-else class="primary full" @click="nextQuestion">{{lesson.index===lesson.list.length-1?'查看探索成果':'继续调查下一条线索'}} <I name="ArrowRight" :size="18"/></button></section><aside class="quiz-companion"><img :src="lesson.submitted?(lesson.selected===currentQ.answer?'/assets/mascot-happy.png':'/assets/mascot-think.png'):'/assets/mascot.png'" alt="工小智陪你答题"/><div><span class="eyebrow">工小智的小提醒</span><p>{{lesson.submitted?'记住判断背后的原因，比一次答对更有意义。':'不用着急，看清情境。涉及转账、密码和身份信息时，多一步核实。'}}</p></div><div class="quiz-stat"><span>本轮答对</span><b>{{lesson.score}} 题</b></div></aside></div>
    </template>
    <section v-else class="result-card"><div class="result-orbit"><img :src="lesson.passed?'/assets/award-guardian.png':'/assets/mascot-think.png'" :alt="lesson.passed?'挑战成功':'继续学习'"/></div><span class="eyebrow">{{lesson.practice?'学习报告':'城市探索报告'}}</span><h1>{{lesson.practice?'又多了一份守护的力量':lesson.passed?'这一站，由你守护！':'再试一次，线索就在眼前'}}</h1><p>{{lesson.practice?'你的学习记录与错题已保存。':lesson.passed?`${lesson.place.name}的异常信号已解除。${lesson.newComplete?'城市印章已收入你的探索护照。':'你已再次完成这个地标的挑战。'}`:'答对至少 2 题即可完成本关，重试时可以再次查看解析。'}}</p><div class="result-stats"><div><strong>{{lesson.score}}<small> / {{lesson.list.length}}</small></strong><span>本轮正确</span></div><div><strong>+{{lesson.gained}}</strong><span>获得体验 i豆</span></div><div><strong>{{coreDone}}<small> / 6</small></strong><span>已守护地标</span></div></div><div v-if="lesson.newComplete" class="unlock-banner"><I name="Sparkles"/> 已解锁 · {{lesson.place.unlock}}</div><div class="result-buttons"><button class="secondary" @click="beginQuiz">再练一次</button><button class="primary" @click="leaveLesson">{{lesson.practice?'返回课堂':'继续探索'}} <I name="ArrowRight" :size="18"/></button></div></section>
   </main>

   <main v-else-if="page==='home'" class="home-page page-enter">
    <div class="welcome-heading"><div><div class="eyebrow">HI, EXPLORER. THE CITY IS YOURS.</div><h1>出发吧，{{state.name}} <span class="wave">✦</span></h1><p>走进长沙的烟火日常，开启你的金融守护之旅。</p></div><button class="quiet-link" @click="openModal('rules')"><I name="CircleHelp" :size="17"/>活动指南 <I name="ArrowUpRight" :size="16"/></button></div>
    <div class="home-columns"><div class="home-main">
     <section class="hero"><div class="hero-image"/><div class="hero-grid"/><div class="hero-content"><span class="hero-kicker"><i/>长沙站 · 城市探索计划 01</span><h2>把长沙走成<br>你的<span>主场。</span></h2><p>一座城，一场冒险。<br>和工小智一起，发现另一面。</p><button class="lime-button" @click="openStory(activePlace)">开启我的探索 <I name="ArrowUpRight" :size="19"/></button><div class="hero-coordinates">28°11′ N &nbsp; 112°58′ E <span>CHANGSHA</span></div></div><div class="mascot-stage"><span class="floating-label"><i/>你的专属探索搭子</span><img src="/assets/mascot.png" alt="工小智驾着悬浮滑板等待与你出发"/><div class="orbit orbit-one"/><div class="orbit orbit-two"/><span class="mascot-name">工小智 <span>ONLINE</span></span></div><span class="hero-star star-one">✦</span><span class="hero-star star-two">✦</span></section>
     <div class="benefits"><button @click="go('map')"><img src="/assets/pin.png" alt=""/><div><b>走长沙</b><span>在城市里，收集新鲜感</span></div><I name="ChevronRight" :size="16"/></button><button @click="go('classroom')"><img src="/assets/shield.png" alt=""/><div><b>学金融</b><span>让每一次判断更有底气</span></div><I name="ChevronRight" :size="16"/></button><button @click="go('rewards')"><img src="/assets/gift.png" alt=""/><div><b>赢好礼</b><span>把探索的快乐带回家</span></div><I name="ChevronRight" :size="16"/></button></div>
     <div class="section-heading"><div><span class="eyebrow">CHOOSE YOUR JOURNEY</span><h2>今天，想怎么逛？</h2></div><span class="muted small">三种节奏，同样精彩</span></div>
     <div class="mode-grid"><button v-for="mode in modes" :key="mode.id" class="mode-card" :class="mode.color" @click="chooseMode(mode.id)"><div class="mode-card-top"><span class="mode-time"><I :name="mode.icon" :size="13"/>{{mode.time}}</span><span v-if="mode.id==='city'" class="recommend">人气路线</span></div><h3>{{mode.name}}<I name="ArrowUpRight" :size="21"/></h3><p>{{mode.label}}</p><div class="mode-art"><img :src="`/assets/maps/${mode.image}`" :alt="`${mode.full}地标路线插画`"/></div><div class="mode-card-bottom"><span>{{mode.ids.length}} 个探索地点 · {{mode.distance}}</span><span class="circle-arrow"><I name="ArrowRight" :size="17"/></span></div></button></div>
     <div class="section-heading shortcuts-heading"><h2>不止于探索</h2><span class="muted small">你的镜界，更多可能</span></div><div class="shortcut-grid"><button v-for="(item,index) in [{id:'story',title:'剧本故事',desc:'走进镜界'},{id:'avatar',title:'虚拟形象',desc:'定义你的样子'},{id:'classroom',title:'反诈课堂',desc:'给安全加点分'},{id:'ranking',title:'探索榜单',desc:'与伙伴同行'}]" :key="item.id" @click="item.id==='ranking'?openModal('ranking'):go(item.id)"><img :src="`/assets/icon-${item.id}.png`" alt=""/><div><b>{{item.title}}</b><span>{{item.desc}}</span></div><I name="ArrowUpRight" :size="16"/></button></div>
     <div class="daily-tip"><span><I name="ShieldCheck" :size="17"/>今日防诈灵感</span><p>“免费”礼物的背后，可能是付费的陷阱。陌生二维码，先核实再扫描。</p><button @click="startPractice(questions.filter(q=>q.place==='wuyi'))">学一招 <I name="ArrowRight" :size="16"/></button></div>
    </div><aside class="home-aside">
     <section class="explorer-card"><div class="card-heading"><span>我的探索身份</span><button class="icon-button" aria-label="编辑数字形象" @click="go('avatar')"><I name="ArrowUpRight" :size="18"/></button></div><div class="profile-scene"><span class="profile-ring"/><AvatarFigure :model-value="state.avatar"/><span class="level-pill">Lv.{{coreDone>=6?3:coreDone>=3?2:1}} {{level}}</span><span class="profile-spark">✧</span></div><h3>{{state.name}}</h3><p>每一步，都在成为更好的自己。</p><div class="profile-numbers"><button @click="go('rewards')"><strong>{{state.points}}<span class="coin">i</span></strong><span>我的 i豆</span></button><button @click="go('profile')"><strong>{{coreDone}}<small>/ 6</small></strong><span>城市印章</span></button></div><button class="outline-button full" @click="go('avatar')"><I name="Palette" :size="16"/>装扮我的数字分身</button></section>
     <section class="mission-card"><div class="card-heading"><h3>探索进行时</h3><span class="live-dot">LIVE</span></div><p>{{currentMode.full}} · {{routeDone===routePlaces.length?'路线已完成':'下一站，等你点亮'}}</p><div class="next-stop"><div class="next-icon"><I :name="activePlace.icon" :size="25"/></div><div><span>NEXT STOP</span><h4>{{activePlace.name}}</h4></div><span class="route-index">{{String(routeDone+1>routePlaces.length?routePlaces.length:routeDone+1).padStart(2,'0')}}</span></div><div class="mission-progress"><span>路线进度</span><b>{{routeDone}} / {{routePlaces.length}}</b></div><div class="progress-track"><i :style="{width:routeDone/routePlaces.length*100+'%'}"/></div><button class="text-blue" @click="go('map')">查看我的路线 <I name="ArrowRight" :size="17"/></button></section>
     <button class="prize-card" @click="go('rewards')"><span class="eyebrow">EXPLORE & GET REWARDED</span><h3>下一程，<br>让好奇心带你起飞。</h3><div class="plane-symbol">✈</div><span class="prize-foot">探索集章 · 解锁机票抽奖资格 <I name="ArrowUpRight" :size="17"/></span><span class="demo-caption">奖品及抽奖仅为参赛演示</span></button>
    </aside></div><footer class="page-footer"><span>工银星启 · 让金融有温度，让探索有意义。</span><span>第十七届「工行杯」金融科技创新大赛</span></footer>
   </main>

   <main v-else-if="page==='map'" class="map-page page-enter">
    <div class="page-heading"><div><span class="eyebrow">YOUR CITY, YOUR ADVENTURE</span><h1>星城探索地图<span class="title-dot">.</span></h1><p>点亮一处地标，读懂一面长沙。</p></div><button class="secondary" @click="guideOpen=!guideOpen"><I name="Route" :size="17"/>路线攻略</button></div>
    <div class="map-mode-tabs"><button v-for="m in modes" :key="m.id" :class="{active:state.mode===m.id}" @click="state.mode=m.id;selected=activePlace"><I :name="m.icon" :size="18"/><span>{{m.full}}</span><small>{{m.time}}</small></button></div>
    <div v-if="guideOpen" class="route-guide"><b>{{currentMode.full}} · {{currentMode.distance}}</b><p>{{routePlaces.map(p=>p.name).join(' → ')}}</p><span>时间为企划建议，未计算实时交通；本页为艺术示意地图。线下出行请使用正式导航确认路线。</span></div>
    <div class="map-layout"><section class="map-canvas"><div class="map-top-note"><span><i/>{{currentMode.full}}</span><small>艺术地图 · 位置示意</small></div><div class="map-image-wrap" :style="{transform:`scale(${scale})`}"><img class="map-art" src="/assets/maps/changsha.png" alt="长沙六大地标插画地图：橘子洲、五一广场、太平老街、杜甫江阁、潮宗街、湖南博物院"/><svg class="map-path" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline :points="routePath" class="route-shadow"/><polyline :points="routePath" class="route-line"/></svg><button v-for="p in places.filter(p=>p.id!=='pozi'||state.mode==='quick')" :key="p.id" class="map-pin" :class="{selected:selected.id===p.id,done:state.completed.includes(p.id),offroute:!currentMode.ids.includes(p.id)}" :style="{left:p.x+'%',top:p.y+'%'}" :aria-label="`${p.name}，${state.completed.includes(p.id)?'已守护':'查看剧情'}`" @click="inspectPlace(p)"><span class="pin-number"><I v-if="state.completed.includes(p.id)" name="Check" :size="16"/><template v-else>{{currentMode.ids.includes(p.id)?currentMode.ids.indexOf(p.id)+1:'·'}}</template></span><span>{{p.name}}<small>{{state.completed.includes(p.id)?'已守护':currentMode.ids.includes(p.id)?'点击探索':'其他路线'}}</small></span></button></div><div class="map-compass"><I name="Navigation" :size="20"/><b>N</b></div><div class="map-tools"><button aria-label="放大地图" @click="scale=Math.min(1.6,scale+.15)"><I name="Plus" :size="19"/></button><button aria-label="缩小地图" @click="scale=Math.max(1,scale-.15)"><I name="Minus" :size="19"/></button><button aria-label="恢复地图全景" @click="scale=1"><I name="LocateFixed" :size="19"/></button></div><span class="map-watermark">CHANGSHA · 长沙</span></section>
    <aside class="map-detail"><div class="selected-place-card"><span class="eyebrow">{{state.completed.includes(selected.id)?'COMPLETED · 已守护':'YOUR NEXT DISCOVERY'}}</span><div class="place-title"><h2>{{selected.name}}</h2><span class="place-emblem"><I :name="selected.icon" :size="25"/></span></div><span class="tag blue-tag">{{selected.category}}</span><p>{{selected.cultural}}</p><div class="place-story"><I name="BookOpen" :size="18"/><div><small>这一站的故事</small><h4>{{selected.title}}</h4></div></div><div class="place-rewards"><span><I name="Star" :size="16"/>首通 +20 i豆</span><span><I name="ShieldCheck" :size="16"/>城市限定印章</span></div><button class="primary full" @click="openStory(selected)">{{state.completed.includes(selected.id)?'重温地标故事':'进入剧情挑战'}} <I name="ArrowRight" :size="18"/></button><button class="outline-button full" @click="scanPlace=selected.id;openModal('navigation')"><I name="Navigation" :size="16"/>前往这里 · 导航演示</button></div><div class="route-list-card"><div class="card-heading"><h3>我的探索动线</h3><span>{{routeDone}} / {{routePlaces.length}}</span></div><button v-for="(p,i) in routePlaces" :key="p.id" class="route-list-item" :class="{active:selected.id===p.id,done:state.completed.includes(p.id)}" @click="inspectPlace(p)"><span class="route-circle"><I v-if="state.completed.includes(p.id)" name="Check" :size="13"/><template v-else>{{i+1}}</template></span><div><b>{{p.name}}</b><small>{{p.category}}</small></div><I name="ChevronRight" :size="15"/></button></div><div class="mascot-tip"><img src="/assets/mascot-happy.png" alt="工小智"/><p>路线可以自由切换，<br>收集到的印章会一直陪着你。</p></div></aside></div>
   </main>

   <main v-else-if="page==='avatar'" class="standard-page avatar-page page-enter"><AvatarStudio v-model="state.avatar" @save="saveAvatar" @close="go('home')"/><div class="wardrobe-note"><I name="Sparkles" :size="18"/><p>预览版开放全部装扮试穿。完成地标挑战，还能在探索护照里收集对应的解锁记录。</p></div></main>

   <main v-else-if="page==='story'" class="standard-page page-enter"><div class="page-heading"><div><span class="eyebrow">STORIES OF THE MIRROR CITY</span><h1>每座城，都有另一面<span class="title-dot">.</span></h1><p>“欺诈暗流”潜入星城。你和工小智，将如何解开这场镜界危机？</p></div><span class="tag blue-tag">6 幕城市故事</span></div><section class="story-intro-banner"><div><span class="eyebrow">主线故事 · 赛博星城的镜界危机</span><h2>发现风险。<br>也发现自己的力量。</h2><p>跟随城市线索，遇见老街的引路人、咖啡店主理人和熟悉的辅导员。每一次判断，都在重建镜界的安全网络。</p><button class="lime-button" @click="openStory(activePlace)">从这里开始 <I name="ArrowUpRight" :size="18"/></button></div><img src="/assets/mascot.png" alt="工小智"/></section><div class="chapter-grid"><button v-for="(p,i) in places.slice(0,6)" :key="p.id" class="chapter-card" @click="openStory(p)"><span class="chapter-number">0{{i+1}}</span><span class="tag" :class="state.completed.includes(p.id)?'green-tag':'blue-tag'">{{state.completed.includes(p.id)?'已守护':p.category}}</span><h3>{{p.title}}</h3><p>{{p.intro}}</p><div><span><I name="MapPin" :size="14"/>{{p.name}}</span><I name="ArrowUpRight" :size="20"/></div></button></div></main>

   <main v-else-if="page==='classroom'" class="standard-page page-enter"><div class="page-heading"><div><span class="eyebrow">A LITTLE KNOWLEDGE, A LOT OF POWER</span><h1>反诈课堂<span class="title-dot">.</span></h1><p>把知识装进口袋，让每一个判断更有底气。</p></div><button class="primary" @click="startPractice()"><I name="Play" :size="17"/>开始练习</button></div><div class="learning-summary"><div><I name="BookOpen" :size="28"/><span><b>42 <small>道</small></b><p>情境知识题</p></span></div><div><I name="ShieldCheck" :size="28"/><span><b>{{state.correct.length}} <small>道</small></b><p>已掌握题目</p></span></div><div><I name="RefreshCw" :size="28"/><span><b>{{state.mistakes.length}} <small>道</small></b><p>待复习错题</p></span></div><button class="text-blue" @click="classFilter='错题本'">打开我的错题本 <I name="ArrowRight" :size="17"/></button></div><div class="filter-bar"><div class="category-tabs"><button v-for="c in ['全部',...new Set(questions.map(q=>q.category)),'错题本']" :key="c" :class="{active:classFilter===c}" @click="classFilter=c">{{c}}</button></div><input v-model="questionSearch" placeholder="搜索题目关键词" aria-label="搜索题目关键词"/></div><div class="question-library"><button v-for="(q,i) in filteredQuestions" :key="q.id" class="library-row" @click="startPractice([q])"><span class="library-index">{{String(i+1).padStart(2,'0')}}</span><div><span class="eyebrow">{{q.category}}</span><h3>{{q.title}}</h3></div><span v-if="state.correct.includes(q.id)" class="mastered"><I name="CheckCheck" :size="17"/>已掌握</span><I name="ChevronRight" :size="20"/></button><div v-if="!filteredQuestions.length" class="empty-state"><I name="ShieldCheck" :size="42"/><h3>{{classFilter==='错题本'?'暂时没有待复习错题':'没有找到匹配的题目'}}</h3><p>换个关键词，或开启一次新的练习吧。</p><button class="secondary" @click="classFilter='全部';questionSearch=''">查看全部题目</button></div></div><div class="source-note"><b>知识参考</b><p>题目为依据公开风险提示编写的原创情境练习，供参赛教育演示使用，未经过银行消保部门审核。</p><a v-for="source in sources" :key="source.url" :href="source.url" target="_blank" rel="noreferrer">{{source.title}} <I name="ExternalLink" :size="12"/></a></div></main>

   <main v-else-if="page==='rewards'" class="standard-page page-enter"><div class="page-heading"><div><span class="eyebrow">GOOD THINGS COME TO EXPLORERS</span><h1>每一份好奇，都有回礼<span class="title-dot">.</span></h1><p>积攒城市的美好，也给自己一点小奖励。</p></div><button class="secondary" @click="openModal('backpack')"><I name="Backpack" :size="18"/>我的背包</button></div><section class="wallet-banner"><div><span>我的体验 i豆</span><h2>{{state.points}}<span class="coin">i</span></h2><p>首次答对 +10 · 地标首通 +20 · 每日签到 +10</p></div><button class="lime-button" @click="claimDaily"><I name="Check" :size="17"/>{{state.daily===today()?'今日已签到':'签到领 10 i豆'}}</button><div class="wallet-spark">✦</div></section><div class="reward-disclaimer"><I name="CircleHelp" :size="17"/>以下积分、商户权益与抽奖均为参赛演示，不可实际兑换或兑付。</div><div class="section-heading"><h2>让探索，兑换成小确幸</h2><span class="muted small">CITY PERKS</span></div><div class="reward-grid"><article v-for="r in rewards" :key="r.id" class="reward-card"><div class="reward-art" :class="r.color"><I :name="r.icon" :size="78"/><span>CHANGSHA LIMITED</span><i>✧</i></div><div class="reward-copy"><h3>{{r.title}}</h3><p>{{r.desc}}</p><div><strong>{{r.cost}} <small>i豆</small></strong><button class="secondary" @click="redeem(r)">{{state.redeemed.includes(r.id)?'已兑换':'兑换体验券'}}</button></div></div></article></div><section class="flight-banner"><div><span class="eyebrow">YOUR NEXT DESTINATION AWAITS</span><h2>从长沙出发，<br>把世界加入下一站。</h2><p>完成六大地标挑战 + 至少一次模拟线下打卡<br>解锁国内往返机票抽奖资格展示。</p><button class="primary" @click="activateTicket">{{state.ticket?'资格已激活':'激活我的抽奖资格'}} <I name="ArrowUpRight" :size="18"/></button><small>演示活动 · 无实际开奖或机票发放</small></div><div class="boarding-pass"><span>STAR JOURNEY / BOARDING PASS</span><div><b>CSX</b><I name="ArrowRight" :size="34"/><b>???</b></div><p>长沙 CHANGSHA <span>你的下一站</span></p><div class="ticket-line"/><div class="boarding-footer"><span>EXPLORER<br><b>{{state.name}}</b></span><I name="Ticket" :size="32"/></div></div></section></main>

   <main v-else-if="page==='profile'" class="standard-page page-enter"><div class="page-heading"><div><span class="eyebrow">EVERY STEP TELLS YOUR STORY</span><h1>我的探索手记<span class="title-dot">.</span></h1><p>那些走过的地方，正在成为你的光。</p></div><button class="secondary" @click="nameDraft=state.name;openModal('settings')"><I name="Settings2" :size="17"/>个人设置</button></div><section class="profile-banner"><div class="large-avatar"><AvatarFigure :model-value="state.avatar"/></div><div><span class="tag blue-tag">{{level}}</span><h2>{{state.name}}</h2><p>和工小智一起，在星城写下属于你的故事。</p><button class="text-blue" @click="go('avatar')">编辑我的数字形象 <I name="ArrowRight" :size="17"/></button></div><div class="profile-overview"><div><strong>{{state.points}}</strong><span>体验 i豆</span></div><div><strong>{{coreDone}}</strong><span>城市印章</span></div><div><strong>{{state.checkins.length}}</strong><span>模拟打卡</span></div></div></section><div class="section-heading"><div><span class="eyebrow">MY CITY PASSPORT</span><h2>把长沙，一站站收藏</h2></div><button class="secondary" @click="downloadPassport"><I name="Download" :size="17"/>下载探索护照</button></div><div class="stamp-grid"><button v-for="(p,i) in places.slice(0,6)" :key="p.id" class="stamp-card" :class="{collected:state.completed.includes(p.id)}" @click="openStory(p)"><div class="stamp-ring"><I :name="p.icon" :size="34"/><span>{{state.completed.includes(p.id)?'已守护':'待探索'}}</span></div><h3>{{p.name}}</h3><small>CHANGSHA · 0{{i+1}}</small></button></div><div class="profile-bottom-grid"><section class="white-card"><div class="card-heading"><h3>成长里程碑</h3><span>{{progress}}%</span></div><div class="achievement-list"><div v-for="(item,i) in [{name:'初阶探索者',desc:'开启你的星城旅程',img:'explorer',done:true},{name:'城市足迹官',desc:'守护 3 个核心地标',img:'city',done:coreDone>=3},{name:'金融守护者',desc:'守护全部 6 个核心地标',img:'guardian',done:coreDone>=6}]" :key="i" :class="{locked:!item.done}"><img :src="`/assets/award-${item.img}.png`" alt=""/><span><b>{{item.name}}</b><small>{{item.desc}}</small></span><I :name="item.done?'Check':'LockKeyhole'" :size="18"/></div></div></section><section class="white-card"><h3>我的探索工具箱</h3><button class="toolbox-row" @click="openModal('backpack')"><I name="Backpack"/><span>装扮与权益背包</span><I name="ChevronRight" :size="17"/></button><button class="toolbox-row" @click="classFilter='错题本';go('classroom')"><I name="BookOpen"/><span>我的错题本 · {{state.mistakes.length}} 道</span><I name="ChevronRight" :size="17"/></button><button class="toolbox-row" @click="openModal('scan')"><I name="ScanLine"/><span>记录城市打卡</span><I name="ChevronRight" :size="17"/></button><button class="toolbox-row" @click="openModal('rules')"><I name="CircleHelp"/><span>活动指南</span><I name="ChevronRight" :size="17"/></button></section></div></main>

   <main v-else-if="page==='community'" class="standard-page page-enter"><div class="page-heading"><div><span class="eyebrow">GOOD ADVENTURES ARE BETTER TOGETHER</span><h1>星启社区<span class="title-dot">.</span></h1><p>看看同频伙伴眼中的长沙。以下为预置体验内容。</p></div><button class="primary" @click="openModal('diary')"><I name="Plus" :size="18"/>写探索日记</button></div><div class="community-grid"><article v-if="state.diary" class="post-card own-diary"><div class="post-body"><span class="eyebrow">MY CHANGSHA DIARY · 仅自己可见</span><h2>我的探索日记</h2><p class="diary-text">{{state.diary}}</p><button class="text-blue" @click="openModal('diary')">继续编辑 <I name="ArrowRight" :size="16"/></button></div></article><article class="post-card" v-for="post in posts" :key="post.id"><div class="post-cover"><img :src="post.cover==='avatar'?'/assets/avatar/showcase.gif':`/assets/maps/${post.cover}`" :alt="post.title"/></div><div class="post-body"><span class="eyebrow">{{post.school}} · 示例动态</span><h2>{{post.title}}</h2><p>{{post.text}}</p><span class="text-blue">{{post.tag}}</span><div class="post-footer"><span><i>{{post.name[0]}}</i>{{post.name}}</span><button :class="{liked:state.likes.includes(post.id)}" @click="like(post.id)"><I name="Heart" :size="18"/>{{post.likes+(state.likes.includes(post.id)?1:0)}}</button></div></div></article></div></main>

   <nav class="mobile-nav" aria-label="移动端导航"><button :class="{active:page==='home'}" @click="go('home')"><I name="Home" :size="21"/><span>首页</span></button><button :class="{active:page==='map'}" @click="go('map')"><I name="Map" :size="21"/><span>地图</span></button><button class="scan-nav" @click="openModal('scan')"><span><I name="ScanLine" :size="25"/></span><small>打卡</small></button><button :class="{active:page==='classroom'}" @click="go('classroom')"><I name="ShieldCheck" :size="21"/><span>课堂</span></button><button :class="{active:page==='profile'}" @click="go('profile')"><I name="UserRound" :size="21"/><span>我的</span></button></nav>
  </div>
  <Transition name="toast"><div v-if="toast" class="toast-message" role="status"><I name="Sparkles" :size="17"/>{{toast}}</div></Transition>
  <Transition name="modal"><div v-if="modal" class="modal-backdrop" @click.self="modal=''"><section ref="dialogEl" class="modal-dialog" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button class="modal-close icon-button" @click="modal=''" aria-label="关闭弹窗"><I name="X" :size="21"/></button>
   <template v-if="modal==='rules'"><span class="eyebrow">YOUR EXPLORER'S GUIDE</span><h2 id="dialog-title">和工小智，一起出发</h2><div class="rule-item" v-for="(r,i) in [{title:'选一条喜欢的路线',text:'极速、城市、深度三种模式随时切换，已经获得的印章会保留。'},{title:'解开城市里的金融谜题',text:'每站 3 道题，答对至少 2 道即可守护地标。首次答对每题 +10 i豆，地标首次通关再得 +20。'},{title:'收集属于你的成长',text:'在数字形象页试穿装扮，在课堂查看全部 42 题与错题，完成探索后下载城市护照。'},{title:'去城市里，记录快乐',text:'打卡与导航可直接模拟体验；六大地标通关且至少一次模拟打卡，可激活抽奖资格展示。'}]" :key="i"><span>0{{i+1}}</span><div><h3>{{r.title}}</h3><p>{{r.text}}</p></div></div><div class="notice">这是参赛预览作品。积分、权益、排行榜与抽奖为演示；导航不调用高德，打卡不验证真实位置。进度只保存在本机浏览器。</div><button class="primary full" @click="modal=''">知道了，开启探索 <I name="ArrowRight" :size="18"/></button></template>
   <template v-else-if="modal==='scan'||modal==='navigation'"><span class="eyebrow">CITY CHECK-IN · 体验演示</span><h2 id="dialog-title">{{modal==='scan'?'把这一站，收进你的足迹':'目的地，就在下一站'}}</h2><div class="scan-frame"><I :name="modal==='scan'?'ScanLine':'Navigation'" :size="68"/><span>{{modal==='scan'?'城市打卡模拟器':'导航路线演示'}}</span><i/></div><label class="field-label" for="checkin-place">选择打卡地标</label><select id="checkin-place" v-model="scanPlace"><option v-for="p in places" :key="p.id" :value="p.id">{{p.name}}</option></select><p class="notice">{{modal==='navigation'?'模拟高德导航的目的地确认与抵达流程，不提供实际道路指引或实时距离。':'无需摄像头与定位权限，点击下方按钮即可演示线下打卡流程。'}} 此操作不会验证真实到访。</p><button class="primary full" @click="checkIn">{{state.checkins.includes(scanPlace)?'已记录此地标':'模拟抵达并打卡'}} <I name="Check" :size="18"/></button></template>
   <template v-else-if="modal==='ranking'"><span class="eyebrow">EXPLORERS TOGETHER</span><h2 id="dialog-title">星城探索榜</h2><p class="muted">示例榜单 · 排名人物为演示数据</p><div class="rank-row" v-for="(r,i) in [{name:'湘江追风者',points:680},{name:'小林同学',points:620},{name:'橘子汽水',points:570},{name:'爱走路的阿星',points:480},{name:state.name,points:state.points}]" :key="i"><b>{{i===4?'我':String(i+1).padStart(2,'0')}}</b><span>{{r.name}}<small>{{i===4?'你的真实本机体验积分':'示例探索者'}}</small></span><strong>{{r.points}} <small>i豆</small></strong></div><button class="primary full" @click="modal='';go('map')">去点亮更多地标 <I name="ArrowRight" :size="18"/></button></template>
   <template v-else-if="modal==='messages'"><span class="eyebrow">A MESSAGE FOR YOU</span><h2 id="dialog-title">你的镜界来信</h2><div class="message-item"><img src="/assets/mascot-happy.png" alt="工小智"/><div><h3>工小智已就位！</h3><p>主理人，长沙的故事正在等你。选一条路线，我们出发吧。</p><small>系统引导</small></div></div><div class="message-item"><I name="Gift" :size="32"/><div><h3>{{state.redeemed.length?'你有新的体验权益':'探索的惊喜，等你领取'}}</h3><p>{{state.redeemed.length?'你兑换的体验券已保存在背包。':'首次答对题目即可获得 i豆，在星启好礼兑换演示权益。'}}</p><small>活动提醒 · 参赛演示</small></div></div></template>
   <template v-else-if="modal==='backpack'"><span class="eyebrow">LITTLE TREASURES FROM YOUR JOURNEY</span><h2 id="dialog-title">我的探索背包</h2><p class="muted">装扮解锁与体验权益都在这里。</p><div class="backpack-item" v-for="r in rewards.filter(r=>state.redeemed.includes(r.id))" :key="r.id"><I :name="r.icon" :size="30"/><div><h3>{{r.title}}</h3><p>已兑换 · 仅演示，不可实际核销</p><small>DEMO-{{r.id.toUpperCase()}}-001</small></div></div><div class="backpack-item" v-for="p in places.filter(p=>state.completed.includes(p.id))" :key="p.id"><I name="Sparkles" :size="29"/><div><h3>{{p.unlock}}</h3><p>{{p.name}} · 挑战解锁记录</p></div></div><div v-if="state.ticket" class="backpack-item"><I name="Ticket" :size="29"/><div><h3>国内往返机票抽奖资格</h3><p>演示资格已激活 · 无实际开奖</p></div></div><div v-if="!state.redeemed.length&&!state.completed.length" class="empty-state"><I name="Backpack" :size="45"/><h3>背包里的故事，还等你来写</h3><p>完成一站探索，收获第一件纪念。</p></div><button class="primary full" @click="go('map')">继续探索 <I name="ArrowRight" :size="18"/></button></template>
   <template v-else-if="modal==='settings'"><span class="eyebrow">MAKE THIS JOURNEY YOURS</span><h2 id="dialog-title">我的探索身份</h2><label for="explorer-name" class="field-label">探索者昵称</label><input id="explorer-name" v-model="nameDraft" maxlength="12" placeholder="为自己起一个探索者昵称" @keyup.enter="saveName"/><p class="muted small">最多 12 个字，仅保存在本机浏览器。</p><button class="primary full" @click="saveName">保存昵称</button><button class="danger-link" @click="modal='reset'">重新开始体验</button></template>
   <template v-else-if="modal==='reset'"><h2 id="dialog-title">重新开启这段旅程？</h2><p class="muted">这会清除本机的答题、积分、形象、打卡、兑换和日记记录。其他项目文件不受影响。</p><button class="primary full" @click="resetProgress">清除体验进度并重新开始</button><button class="secondary full" @click="modal=''">保留当前进度</button></template>
   <template v-else-if="modal==='diary'"><span class="eyebrow">MY CHANGSHA DIARY</span><h2 id="dialog-title">今天的长沙，有什么惊喜？</h2><textarea v-model="shareText" rows="6" maxlength="400" placeholder="写下一段探索心情……" aria-label="探索日记"/><p class="muted small">{{shareText.length}} / 400 · 仅保存到本机演示，不对外发布</p><button class="primary full" @click="share"><I name="Check" :size="18"/>保存探索日记</button></template>
  </section></div></Transition>
 </div>
</template>
